"""user add fields

Revision ID: d9daeb300f86
Revises: 880e14a7eb77
Create Date: 2025-05-04 17:58:24.131226

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9daeb300f86"
down_revision = "880e14a7eb77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_history", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id", "user_device_type"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("surname", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("patronymic", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("patronymic")
        batch_op.drop_column("surname")
        batch_op.drop_column("name")

    with op.batch_alter_table("auth_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
