"""init2

Revision ID: 099611f0d67d
Revises: c2af1c419dac
Create Date: 2025-04-30 17:32:34.751835

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "099611f0d67d"
down_revision = "c2af1c419dac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
